import 'package:audioplayers/audioplayers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Plays the stone and capture sound effects (assets/sounds, generated by
/// tool/gen_sounds.py). Failures are ignored - sound is never essential.
class SoundService {
  final _stone = AudioPlayer();
  final _capture = AudioPlayer();
  bool _ready = false;

  Future<void> _init() async {
    if (_ready) return;
    _ready = true;
    for (final (player, file) in [
      (_stone, 'sounds/stone.wav'),
      (_capture, 'sounds/capture.wav'),
    ]) {
      await player.setPlayerMode(PlayerMode.lowLatency);
      await player.setReleaseMode(ReleaseMode.stop);
      await player.setSource(AssetSource(file));
    }
  }

  /// A stone was placed; [captured] stones were removed by it.
  Future<void> stonePlayed(int captured) async {
    try {
      await _init();
      await _stone.stop();
      await _stone.resume();
      if (captured > 0) {
        await Future<void>.delayed(const Duration(milliseconds: 110));
        await _capture.stop();
        await _capture.resume();
      }
    } catch (_) {}
  }

  void dispose() {
    _stone.dispose();
    _capture.dispose();
  }
}

final soundServiceProvider = Provider<SoundService>((ref) {
  final s = SoundService();
  ref.onDispose(s.dispose);
  return s;
});
